### PR TITLE
Update AMI in cloudformation

### PR DESCRIPTION
**Pull request by rvaralda**

### CODE REVIEW

**Comment by gene1wood** [comment]
What process produced this new AMI that's referenced?

**Comment by gene1wood** [comment]
And does it capture the manual change described in #36

**Comment by rvaralda** [comment]
There is no process by now, I've created it manually.
Yes, I just created this new AMI, it must contain your changes.

**Review by duallain — APPROVED** [review]
Seems ok to me - changing the key seems reasonable, updating the ami is good. Some worries about the ami becoming orphaned at some point, but this is better than before so 👍 from me.

**Pull request merged**
